apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL:  https://github.com/novalytics/grafana-training
    targetRevision: HEAD
    ref: <customizable reference>
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: latest
    helm:
      values: |
        service:
          type: LoadBalancer
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local
                access: proxy
                isDefault: true
              - name: loki
                type: loki
                url: http://loki.monitoring.svc.cluster.local
                access: proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
